# Generated code do not commit.
file(TO_CMAKE_PATH "C:\\Flutter\\flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "R:\\ROCOTOYZ FILES\\MOBILE APP - FLUTTER FIREBASE\\PARKBAI\\PARKBAI" PROJECT_DIR)

set(FLUTTER_VERSION "1.0.0+1" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 0 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 0 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 1 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=C:\\Flutter\\flutter"
  "PROJECT_DIR=R:\\ROCOTOYZ FILES\\MOBILE APP - FLUTTER FIREBASE\\PARKBAI\\PARKBAI"
  "FLUTTER_ROOT=C:\\Flutter\\flutter"
  "FLUTTER_EPHEMERAL_DIR=R:\\ROCOTOYZ FILES\\MOBILE APP - FLUTTER FIREBASE\\PARKBAI\\PARKBAI\\windows\\flutter\\ephemeral"
  "PROJECT_DIR=R:\\ROCOTOYZ FILES\\MOBILE APP - FLUTTER FIREBASE\\PARKBAI\\PARKBAI"
  "FLUTTER_TARGET=R:\\ROCOTOYZ FILES\\MOBILE APP - FLUTTER FIREBASE\\PARKBAI\\PARKBAI\\lib\\main.dart"
  "DART_DEFINES=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC9mNDBlOTc2YmVkZmY1N2U2OWUxYjNkODlhN2MyYTNjNjE3YTAzZGFkLw=="
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=R:\\ROCOTOYZ FILES\\MOBILE APP - FLUTTER FIREBASE\\PARKBAI\\PARKBAI\\.dart_tool\\package_config.json"
)
